version: "3"
services:
  app:
    hostname: hatoka-mediarating-app
    image: "local/hatoka/mediarating-app:latest"
    ports:
      - "4200:80"
    volumes:
      - ./app/src/assets/config:/usr/share/nginx/html/assets/config
