version: "3"
services:
  service:
    hostname: hatoka-mediarating-service
    image: "local/hatoka/mediarating-service:latest"
    ports:
      - "5005:7090"
      - "8090:8090"
      - "9090:9090"
    env_file:
      - ".env"
