version: "3"
services:
  service:
    hostname: hatoka-mediarating-service
    image: "local/hatoka/mediarating-service:latest"
    ports:
      - "5005:7090"
      - "8090:8090"
      - "9090:9090"
    env_file:
      - ".env"
  app:
    hostname: hatoka-mediarating-app
    image: "local/hatoka/mediarating-app:latest"
    ports:
      - "4200:80"
    volumes:
      - ./app/src/assets/config:/usr/share/nginx/html/assets/config
